apiVersion: v1
kind: Service
metadata:
  name: go-app-service
spec:
  type: NodePort
  selector:
    app: go-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
    - protocol: TCP
      port: 6060
      targetPort: 6060
      name: pprof
    - protocol: TCP
      port: 40000
      targetPort: 40000
      name: delve-debug